spring.application.name=DeportLink
spring.docker.compose.enabled=false

# Configuracion de la base de datos MySQL (usando variables de entorno)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#jwt.secret=${JWT_SECRET}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Para que Hibernate maneje las tablas automaticamente:
spring.jpa.hibernate.ddl-auto=update
